[phases.setup]
nixPkgs = ['...', 'google-chrome', 'glib', 'nss', 'nspr', 'atk', 'at-spi2-atk', 'libdrm', 'mesa', 'expat', 'libxcb', 'libX11', 'libXcomposite', 'libXdamage', 'libXext', 'libXfixes', 'libXrandr', 'libgbm', 'pango', 'cairo', 'asound', 'cups']
